apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: semoss
  name: model-deployer-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "services"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]