#RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-deployer-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: model-deployer
  namespace: default
roleRef:
  kind: Role
  name: model-deployer-role
  apiGroup: rbac.authorization.k8s.io