# DaemonSet for L4 GPU Pool
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rcs-image-puller-l4
  namespace: semoss
spec:
  selector:
    matchLabels:
      name: rcs-image-puller
      pool: l4-gpu
  template:
    metadata:
      labels:
        name: rcs-image-puller
        pool: l4-gpu
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: "l4-gpu-pool"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: rcs-image-puller
        image: docker.semoss.org/genai/remote-client-server:2025-02-21-1936
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
      imagePullSecrets:
      - name: CHANGE-ME