apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "florence-2-large"
  namespace: "huggingface-models"
spec:
  predictor:
    serviceAccountName: kube-model-deployer-sa
    containers:
    - name: kserve-container
      image: docker.semoss.org/genai/cfg-ms-models/florence-gpu:latest
      env:
        - name: MODEL_ID
          value: microsoft/Florence-2-large
        - name: MODEL_NAME
          value: florence-2-large
      resources:
        requests:
          memory: "10Gi"
          nvidia.com/gpu: "1"
        limits:
          memory: "16Gi"
          nvidia.com/gpu: "1"