apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "florence-2-large"
  namespace: "huggingface-models"
spec:
  predictor:
    serviceAccountName: kube-model-deployer-sa
    containers:
    - name: kserve-container
      image: docker.semoss.org/genai/cfg-ms-models/florence-gpu:2025-03-18-2046
      env:
        - name: MODEL_ID
          value: microsoft/Florence-2-large
        - name: MODEL_NAME
          value: florence-2-large
        - name: MODEL_FILES_PATH
          value: "/mnt/models"
        - name: STORAGE_URI
          value: "oci://docker.semoss.org/genai/cfg-ms-models/oci/florence-2-large:2025-03-18-1354"
      resources:
        requests:
          memory: "10Gi"
          nvidia.com/gpu: "1"
        limits:
          memory: "16Gi"
          nvidia.com/gpu: "1"