apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "gliner-multi-v2-1"
  namespace: "huggingface-models"
  annotations:
    deployment.kubernetes.io/revision: "2" 
spec:
  predictor:
    serviceAccountName: kube-model-deployer-sa
    containers:
    - name: kserve-container
      image: docker.semoss.org/genai/cfg-ms-models/gliner-cpu:2025-03-19-1251
      env:
        - name: MODEL_ID
          value: urchade/gliner_multi-v2.1
        - name: MODEL_NAME
          value: gliner-multi-v2-1
        - name: MODEL_FILES_PATH
          value: "/mnt/models"
        - name: STORAGE_URI
          value: "oci://docker.semoss.org/genai/cfg-ms-models/oci/gliner_multi-v2-1:2025-03-18-1737"
      resources:
        requests:
          memory: "10Gi"
          cpu: "1"
        limits:
          memory: "14Gi"
          cpu: "2"