apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "roberta-base-go-emotions"
  namespace: "huggingface-models"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
      - --model_name=roberta-base-go-emotions
      - --model_id=SamLowe/roberta-base-go_emotions
      
      resources:
        requests:
          memory: "10Gi"
          cpu: "1"
        limits:
          memory: "14Gi"
          cpu: "2"