apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: semoss
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes