name: Docker Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set date environment variable
        run: echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Docker Build
        run: |
          export DOCKER_TLS_CERTDIR=""
          ls -lah
          pwd
          echo ${{ secrets.DOCKER_PASS}} | docker login ${{ vars.DOCKER_PRIVATE }} --username ${{ secrets.DOCKER_USER}} --password-stdin
          echo "Docker login succeeded"
          echo ${{ secrets.SEMOSS_DOCKER_PASS}} | docker login ${{ vars.DOCKER_SEMOSS }} --username ${{ secrets.SEMOSS_DOCKER_USER}} --password-stdin
          echo "SEMOSS docker login succeeded"
          docker build . -t ${{ vars.DOCKER_PRIVATE }}/genai/kubernetes-model-scaler:$date
          docker tag ${{ vars.DOCKER_PRIVATE }}/genai/kubernetes-model-scaler:$date ${{ vars.DOCKER_SEMOSS }}/genai/kubernetes-model-scaler:$date
          docker push ${{ vars.DOCKER_SEMOSS }}/genai/kubernetes-model-scaler:$date
          docker push  ${{ vars.DOCKER_PRIVATE }}/genai/kubernetes-model-scaler:$date